import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CustomersProvider } from "@/context/CustomerContext";
import { ProductsProvider } from "@/context/ProductContext";
import LayoutHeaderComp from "@/components/layoutheader/LayoutHeaderComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tax Invoice WEB",
  description: "Generated by ROHIT",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const {
  //   customers,
  //   products,
  // }: { customers: CustomerTypes[]; products: ProductTypes[] } =
  //   await fetchInitialData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomersProvider >
          <ProductsProvider >
            <LayoutHeaderComp />
            <main className="container mx-auto py-12 px-10">{children}</main>
          </ProductsProvider>
        </CustomersProvider>
      </body>
    </html>
  );
}
